In [1]:
!pip install docx2txt
import docx2txt

In [18]:
requirement = docx2txt.process(r'C:\Users\chethan mk\Downloads\NLP\requirement.docx')
resume = docx2txt.process(r'C:\Users\chethan mk\Downloads\NLP\nlpresume.docx')
#resume = docx2txt.process(r'C:\Users\chethan mk\Downloads\NLP\nlpresume2.docx')

In [3]:
print(resume)

Chethan MK

Data Scientist

84978000266

chethanmudbasallar@gmail.com



Carrier: Have 6 months of experience in Data Science. Have experience in building complete end-to-end Machine Learning models

Skills :

Machine Learning Algorithms

Statistics and Maths

Feature Engineering

Data Analysis

SQL

Pandas, PySpark, H2O (Data Frame )


In [4]:
print(requirement)

Hi All,

We are looking for a Machine Learning Engineer, location is in Bengaluru.

Required Skills:

Data analysis 

Feature engineering

Metrics involved in Machine Learning

Maths and Statistics

Roles and Responsibility:

Plays the main role in deciding and selecting machine learning libraries for a given task

Analysis and checks the suitability of an algorithm


In [5]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\chethan
[nltk_data]     mk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re
from nltk.tokenize import WhitespaceTokenizer

ps = PorterStemmer()
ws = WordNetLemmatizer()
words = ws.lemmatize(requirement)
#words = nltk.word_tokenize(requirement)
words = re.findall(r'\w+', requirement)
words = list(filter(lambda sub: sub.isalpha(), words))

stop_words = set(stopwords.words('english'))

filtered_requirement = []
for w in words:
    if w not in stop_words:
        filtered_requirement.append(w)

In [7]:
filtered_requirement

['Hi',
 'All',
 'We',
 'looking',
 'Machine',
 'Learning',
 'Engineer',
 'location',
 'Bengaluru',
 'Required',
 'Skills',
 'Data',
 'analysis',
 'Feature',
 'engineering',
 'Metrics',
 'involved',
 'Machine',
 'Learning',
 'Maths',
 'Statistics',
 'Roles',
 'Responsibility',
 'Plays',
 'main',
 'role',
 'deciding',
 'selecting',
 'machine',
 'learning',
 'libraries',
 'given',
 'task',
 'Analysis',
 'checks',
 'suitability',
 'algorithm']

In [8]:
# # sentences = nltk.sent_tokenize(resume)
# # print(sentences)
# sentences = re.findall(r'\w+', resume)
# #sentences = re.findall(r'^[a-zA-z]', resume)
# print(sentences)
# sentences = list(filter(lambda sub: sub.isalpha(), sentences))
# print(sentences)
# # for senw in sentences:
# #     words = nltk.word_tokenize(senw)
# #     print(words)
# # for i in range (len(sentences)):
# #     words = nltk.word_tokenize(sentences[i])
# #     print(words)

In [9]:
# words = re.findall(r'\w+', resume)
# words
# words = list(filter(lambda sub: sub.isalpha(), sentences))
# words

In [10]:
ws = WordNetLemmatizer()
resume = resume.lower()

# sentences = re.findall(r'\w+', words)
# sentences = list(filter(lambda sub: sub.isalpha(), sentences))
words = ws.lemmatize(resume)
#words = nltk.word_tokenize(resume)
words = re.findall(r'\w+', resume)
words = list(filter(lambda sub: sub.isalpha(), words))

stop_words = set(stopwords.words('english'))
filtered_resume = []
for w in words:
    if w not in stop_words:
        filtered_resume.append(w)
# print(sentences)
# corpus = []
# for i in range(len(words)):
#     res = words[i]
#     res = res.lower()
#     res = res.split(" ")
#     res = [ws.lemmatize(word) for word in res if not word in set(stopwords.words('english'))]
#     res = ' '.join(res)
#     corpus.append(res)

# sentences = nltk.sent_tokenize(resume)
# for i in range(len(sentences)):
#     words = nltk.word_tokenize(sentences[i])
# #words = nltk.word_tokenize(sentences)
# corpus = []
# for i in range(len(words)):
#     res = [sub for sub in words[i] if sub.isalpha()]
# #     res = re.sub('[^a-zA-Z]',"", words[i])
# #     res = res.lower()
# #     res = res.split(" ")
#     res = [ws.lemmatize(word) for word in res if not word in set(stopwords.words('english'))]
#     res = ' '.join(res)
#     corpus.append(res)
# # print(res)

In [11]:
print("fr:",filtered_resume)
print("fr:",filtered_requirement)
print(type(filtered_resume))

fr: ['chethan', 'mk', 'data', 'scientist', 'chethanmudbasallar', 'gmail', 'com', 'carrier', 'months', 'experience', 'data', 'science', 'experience', 'building', 'complete', 'end', 'end', 'machine', 'learning', 'models', 'skills', 'machine', 'learning', 'algorithms', 'statistics', 'maths', 'feature', 'engineering', 'data', 'analysis', 'sql', 'pandas', 'pyspark', 'data', 'frame']
fr: ['Hi', 'All', 'We', 'looking', 'Machine', 'Learning', 'Engineer', 'location', 'Bengaluru', 'Required', 'Skills', 'Data', 'analysis', 'Feature', 'engineering', 'Metrics', 'involved', 'Machine', 'Learning', 'Maths', 'Statistics', 'Roles', 'Responsibility', 'Plays', 'main', 'role', 'deciding', 'selecting', 'machine', 'learning', 'libraries', 'given', 'task', 'Analysis', 'checks', 'suitability', 'algorithm']
<class 'list'>


In [19]:
requirement = requirement.lower()

In [20]:
requirement

'hi all,\n\nwe are looking for a machine learning engineer, location is in bengaluru.\n\nrequired skills:\n\ndata analysis \n\nfeature engineering\n\nmetrics involved in machine learning\n\nmaths and statistics\n\nroles and responsibility:\n\nplays the main role in deciding and selecting machine learning libraries for a given task\n\nanalysis and checks the suitability of an algorithm'

In [23]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [24]:
X_list = word_tokenize(requirement) 
Y_list = word_tokenize(resume)
  
# sw contains the list of stopwords
sw = stopwords.words('english') 
l1 =[];l2 =[]
  
# remove stop words from the string
X_set = {w for w in X_list if not w in sw} 
Y_set = {w for w in Y_list if not w in sw}
  
# form a set containing keywords of both strings 
rvector = X_set.union(Y_set) 
for w in rvector:
    if w in X_set: l1.append(1) # create a vector
    else: l1.append(0)
    if w in Y_set: l2.append(1)
    else: l2.append(0)
c = 0
  
# cosine formula 
for i in range(len(rvector)):
        c+= l1[i]*l2[i]
cosine = c / float((sum(l1)*sum(l2))**0.5)
print("similarity: ", cosine)

similarity:  0.08585457105482137


In [12]:
# Bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(filtered_requirement)
cm = cv.transform(filtered_resume)

In [ ]:
print(count_matrix)
print(cm)

In [13]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(count_matrix, cm)
print(sim)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
requirement = requirement.lower()

In [ ]:
resume = resume.lower()

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(requirement)
cm = cv.transform(resume)

In [ ]:
# tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer()
count_matrix = tv.fit_transform(corpusreq)
cm = tv.transform(corpus)

In [ ]:
print(corpusreq)

In [ ]:
print(count_matrix)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances
sim = cosine_similarity(count_matrix, cm)
print(sim)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances
cosine_distances(count_matrix, cm)

In [ ]:
from gensim.models import Word2Vec

In [ ]:
model = Word2Vec()

In [ ]:
model.

In [ ]:
Word2Vec.

In [ ]:
s0 = requirement.lower()
s1 = requirement.lower()

In [ ]:
print(model)

In [ ]:
import numpy as np

In [ ]:
def preprocess(s):
    return [i.lower() for i in s.split()]

def get_vector(s):
    return np.sum(np.array([model[i] for i in preprocess(s)]), axis=0)

from scipy import spatial
print('s0 vs s1 ->',1 - spatial.distance.cosine(get_vector(s0), get_vector(s1)))

In [ ]:
from sklearn.feature_extraction.text import 